name: Publish Release to Maven Central

on:
  push:
    tags:
      - "*.*.*"

jobs:
  publish:

    runs-on: ubuntu-latest
    if: github.repository == 'OpenAttribution/oa-android-sdk'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract Version from libs.versions.toml
        id: extract-version
        run: |
            version=$(awk -F' = ' '/^oaReleaseVersion/{print $2}' gradle/libs.versions.toml | tr -d '"')
            echo "VERSION=$version" >> $GITHUB_ENV

      - name: Get release notes
        run: |
          echo "RELEASE_NOTES<<EOF" >> $GITHUB_ENV
          echo "$(awk '/^## [^ ]/{if (found) exit; found=1} found' CHANGELOG.md)" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Set version for tag
        run: |
          echo "ORG_GRADLE_PROJECT_VERSION_NAME=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Install JDK
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17

      - uses: gradle/actions/setup-gradle@v4

      - name: Publish
        run: ./gradlew publishAndReleaseToMavenCentral
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          body: ${{ env.RELEASE_NOTES }}
        if: ${{ env.RELEASE_NOTES != '' }}
